export { PrismaClient, Prisma } from '@prisma/client';

// Enums da admissão exportados como VALOR (usados em runtime: switch, Object.values, etc.).
export {
  StatusAdmissao,
  TipoDocumentoAdmissional,
  StatusDocumentoAdmissional,
  ResultadoExameAdmissional,
  StatusSolicitacaoAcesso,
  // Alteração contratual (usados como valor em runtime)
  TipoAlteracaoContratual,
  StatusAlteracaoContratual,
  PapelAssinante,
  StatusAssinatura,
  // Offboarding (usados como valor em runtime)
  OrigemOffboarding,
  TipoDesligamento,
  FormaAssinatura,
  StatusOffboarding,
  PapelAssinanteOffboarding,
  CategoriaItemEncerramento,
  StatusItemEncerramento,
  TipoRespostaItem,
  // Notificações internas (usado como valor em runtime)
  TipoNotificacao,
} from '@prisma/client';

export type {
  Usuario,
  Vaga,
  Candidato,
  Candidatura,
  CurriculoProcessado,
  Embedding,
  Score,
  Mensagem,
  Entrevista,
  PerguntaEntrevista,
  PerguntaPadrao,
  RespostaEntrevista,
  AvaliacaoEntrevista,
  Transcricao,
  AnaliseVoz,
  WebhookRecebido,
  RegistroAuditoria,
  Admissao,
  DocumentoAdmissional,
  ExameAdmissional,
  EventoAdmissao,
  SolicitacaoAcesso,
  Notificacao,
  StatusVaga,
  StatusCandidatura,
  TipoScore,
  CanalMensagem,
  StatusMensagem,
  StatusEntrevista,
  OrigemAvaliacao,
  OrigemPergunta,
  StatusResposta,
  RecomendacaoPainel,
  PapelUsuario,
  // Alteração contratual — tipos das tabelas novas
  Cargo,
  CargoLotacao,
  Unidade,
  CentroCusto,
  Colaborador,
  SolicitacaoAlteracaoContratual,
  ItemAlteracaoContratual,
  AssinaturaAlteracaoContratual,
  EventoAlteracaoContratual,
  ExecucaoAlteracaoContratual,
  // Offboarding — tipos das tabelas novas
  Procurador,
  SolicitacaoOffboarding,
  AssinaturaOffboarding,
  ItemEncerramentoOffboarding,
  EventoOffboarding,
  ConviteOffboarding,
} from '@prisma/client';
