export { PrismaClient, Prisma } from '@prisma/client';
export type {
  Usuario,
  Vaga,
  Candidato,
  Candidatura,
  CurriculoProcessado,
  Embedding,
  Score,
  Mensagem,
  Entrevista,
  PerguntaEntrevista,
  AvaliacaoEntrevista,
  Transcricao,
  AnaliseVoz,
  WebhookRecebido,
  RegistroAuditoria,
  StatusVaga,
  StatusCandidatura,
  TipoScore,
  CanalMensagem,
  StatusMensagem,
  StatusEntrevista,
  OrigemAvaliacao,
  RecomendacaoPainel,
  PapelUsuario,
} from '@prisma/client';
